# Generated by Django 5.1.6 on 2025-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='notes',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_notes',
            field=models.TextField(blank=True, help_text='Special requests or notes', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='staff_notes',
            field=models.TextField(blank=True, help_text='Notes for staff only', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='accepts_card',
            field=models.BooleanField(default=False, help_text='Accept card payments'),
        ),
        migrations.AddField(
            model_name='business',
            name='accepts_cash',
            field=models.BooleanField(default=True, help_text='Accept cash payments'),
        ),
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('barbershop', 'Barbershop'), ('salon', 'Beauty Salon'), ('spa', 'Spa & Wellness')], default='barbershop', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='city',
            field=models.CharField(default='Cairo', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='has_parking',
            field=models.BooleanField(default=False, help_text='Parking available'),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.CharField(blank=True, help_text='Instagram handle', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_wheelchair_accessible',
            field=models.BooleanField(default=False, help_text='Wheelchair accessible'),
        ),
        migrations.AddField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='WhatsApp number for bookings', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio or introduction'),
        ),
        migrations.AddField(
            model_name='employee',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(blank=True, help_text='e.g., Senior Barber, Hair Stylist', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('haircut', 'Haircut'), ('shave', 'Shave'), ('color', 'Hair Color'), ('styling', 'Hair Styling'), ('facial', 'Facial'), ('other', 'Other')], default='haircut', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='image1',
            field=models.ImageField(blank=True, help_text='Gallery image 1', null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image2',
            field=models.ImageField(blank=True, help_text='Gallery image 2', null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image3',
            field=models.ImageField(blank=True, help_text='Gallery image 3', null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image4',
            field=models.ImageField(blank=True, help_text='Gallery image 4', null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='main_image',
            field=models.ImageField(help_text='Main display image of your salon', upload_to='business/main/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text='\n    Format: {\n        "0": {"open": "09:00", "close": "18:00", "is_closed": false},\n        "1": {"open": "09:00", "close": "18:00", "is_closed": false},\n        ...\n    }\n    '),
        ),
    ]
