# Generated by Django 5.1.6 on 2025-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_alter_booking_options_alter_business_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name_plural': 'businesses'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='staff_notes',
        ),
        migrations.RemoveField(
            model_name='business',
            name='accepts_card',
        ),
        migrations.RemoveField(
            model_name='business',
            name='accepts_cash',
        ),
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='business',
            name='city',
        ),
        migrations.RemoveField(
            model_name='business',
            name='has_parking',
        ),
        migrations.RemoveField(
            model_name='business',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='business',
            name='is_wheelchair_accessible',
        ),
        migrations.RemoveField(
            model_name='business',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='business/gallery/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='main_image',
            field=models.ImageField(upload_to='business/main/'),
        ),
        migrations.AlterField(
            model_name='business',
            name='opening_hours',
            field=models.JSONField(default=dict, help_text='\n    Format: {\n        "0": {"open": "09:00", "close": "18:00"},\n        "1": {"open": "09:00", "close": "18:00"},\n        ...\n    }\n    '),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
