# Generated by Django 5.1.6 on 2025-03-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_alter_booking_options_alter_business_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('barbershop', 'Barbershop'), ('salon', 'Beauty Salon'), ('spa', 'Spa & Wellness'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(help_text='Tell us about your business')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp number (optional)', max_length=20, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('instagram', models.CharField(blank=True, help_text='Instagram handle (optional)', max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, help_text='Facebook page URL (optional)', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='Business website (optional)', null=True)),
                ('years_in_business', models.PositiveIntegerField(help_text='How many years has your business been operating?')),
                ('number_of_employees', models.PositiveIntegerField(help_text='How many employees do you have?')),
                ('services_offered', models.TextField(help_text='List your main services')),
                ('has_business_license', models.BooleanField(default=False, help_text='Do you have a valid business license?')),
                ('business_license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, help_text="Any additional information you'd like to share", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info', 'More Information Needed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for administrators', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Request',
                'verbose_name_plural': 'Business Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
