# Generated by Django 5.1.6 on 2025-03-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_businessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessrequest',
            name='owner_name',
        ),
    ]
