# Generated by Django 5.1.6 on 2025-03-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_remove_businessrequest_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='businessrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
