# Generated by Django 5.1.6 on 2025-03-07 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0010_convert_bookings_to_timeslots'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shift',
            name='unique_employee_shift',
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('recurring', 'Recurring Weekly'), ('one_time', 'One-time Special')], default='recurring', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('shift_type', 'recurring')), fields=('employee', 'day_of_week', 'start_time'), name='unique_employee_shift'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('shift_type', 'one_time')), fields=('employee', 'specific_date', 'start_time'), name='unique_employee_one_time_shift'),
        ),
    ]
