# Generated by Django 5.1.6 on 2025-03-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0011_remove_shift_unique_employee_shift_shift_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='shift',
            name='unique_employee_shift',
        ),
        migrations.RemoveConstraint(
            model_name='shift',
            name='unique_employee_one_time_shift',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='specific_date',
        ),
        migrations.AlterField(
            model_name='shift',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('employee', 'day_of_week', 'start_time', 'end_time'), name='unique_employee_shift'),
        ),
    ]
