# Generated by Django 5.1.6 on 2025-03-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0012_alter_shift_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='bookings', to='businesses.service'),
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slots',
            field=models.ManyToManyField(related_name='bookings', to='businesses.timeslot'),
        ),
    ]
